export enum VendorRoutes {
  register = "/api/vendor/register",
  login = "/api/vendor/login",
  otp_resend = "/api/vendor/otp/resend",
  otp_verify = "/api/vendor/otp/verify",
  product_upload = "/api/vendor/products/upload",
  delivery_pricing_add = "/api/vendor/delivery/pricing/add",
  delivery_pricing_get = "/api/vendor/delivery/pricing/get",
  banner_add = "/api/vendor/advertisement/add",
  banner_get = "/api/vendor/advertisement/get",
  category_delete = "/api/category/delete",
  category_update = "/api/category/update",
  advertisement_delete = "/api/advertisement/delete",
  advertisement_update = "/api/advertisement/update",
  admin_post_delete = "/api/admin/post/delete",
  admin_post_update = "/api/admin/post/update",
}
