export enum Routes {
  products_get = "/api/products/get",
  category_add = "/api/categories/add",
  categories_get = "/api/categories/get",
  admin_login = "",
  admin_register = "",
  merit_add = "/api/merits/add",
  merit_get = "/api/merits/get",
  auth_login = "/api/auth/login",
  vendors_get = "/api/vendors/get",
  product_approve_decline = "/api/product/approve_decline",
  users_get = "/api/users/get",
  vendor_acccount_status = "/api/vendor/account/status",
  pressing_cat_add = "/api/pressing/cat/add",
  pressing_cat_get = "/api/pressing/cat/get",
  pressing_cat_update = "/api/pressing/cat/update",
  package_add = "/api/package/add",
  package_get = "/api/package/get",
  package_order_add = "/api/package/order/add",
  package_order_get = "/api/package/orders/get",
  admin_comments_add = "/api/admin/comments/add",
  admin_comments_get = "/api/admin/comments/get",
  admin_comments_remove = "/api/admin/comments/remove",
  package_like = "/api/package/like",
  package_favorite = "/api/package/favorite",
}
